# Generated by Django 6.1 on 2026-08-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackextractionrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20),
        ),
    ]
